/**
 * Injects the pre-built RESUMEN sheet (native, professionally styled Excel
 * charts) from templates/dashboard_chart_template.xlsx into the already
 * written output Excel file.
 *
 * Strategy: both .xlsx files are ZIP archives. The RESUMEN sheet subtree is
 * copied with jszip under fresh part names: worksheet, drawing, N charts and
 * each chart's chartStyle/chartColorStyle parts (these carry the "Estilos de
 * grafico" look). Then workbook.xml / workbook.xml.rels / [Content_Types].xml
 * are patched.
 *
 * The chart XML references data by sheet NAME ('Dashboard_Data'!...), so the
 * charts populate automatically from the hidden Dashboard_Data sheet written
 * by ExcelJS. Series ranges are trimmed to the REAL supplier count, and the
 * doughnut chart is dropped entirely when there is only one supplier (a 100%
 * donut carries no information).
 *
 * The template's RESUMEN sheet must contain NO cell values and NO styled
 * cells: style indexes and sharedStrings would resolve against the target
 * workbook and trigger Excel's repair dialog. It is generated by
 * scripts/build-chart-template.ps1, which enforces this.
 */

import * as fs from "node:fs/promises";
import JSZip from "jszip";

const CHART_SHEET_NAME = "RESUMEN";
const WORKSHEET_TYPE =
  "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet";

const CT_WORKSHEET = "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml";
const CT_DRAWING = "application/vnd.openxmlformats-officedocument.drawing+xml";
const CT_CHART = "application/vnd.openxmlformats-officedocument.drawingml.chart+xml";
const CT_CHART_STYLE = "application/vnd.ms-office.chartstyle+xml";
const CT_CHART_COLORS = "application/vnd.ms-office.chartcolorstyle+xml";

// ── helpers ──────────────────────────────────────────────────────────────────

function maxNumberedFiles(zip: JSZip, pattern: RegExp): number {
  let max = 0;
  zip.forEach((relPath) => {
    const m = relPath.match(pattern);
    if (m) max = Math.max(max, Number(m[1]));
  });
  return max;
}

function maxRId(relsXml: string): number {
  let max = 0;
  for (const m of relsXml.matchAll(/Id="rId(\d+)"/g)) {
    max = Math.max(max, Number(m[1]));
  }
  return max;
}

function maxSheetId(workbookXml: string): number {
  let max = 0;
  for (const m of workbookXml.matchAll(/sheetId="(\d+)"/g)) {
    max = Math.max(max, Number(m[1]));
  }
  return max;
}

async function readZipFile(zip: JSZip, name: string): Promise<string> {
  const f = zip.file(name);
  if (!f) throw new Error(`injectDashboardCharts: expected ${name} in ZIP`);
  return f.async("string");
}

async function readZipFileOptional(zip: JSZip, name: string): Promise<string | null> {
  const f = zip.file(name);
  return f ? f.async("string") : null;
}

/**
 * The template charts reference 'Dashboard_Data'!$X$2:$X$7 (6 supplier slots).
 * Trims the series end row so the charts only cover the real suppliers written
 * by writeDashboardData (no empty categories / zero bars).
 */
function trimChartRanges(chartXml: string, supplierCount: number): string {
  if (!Number.isInteger(supplierCount) || supplierCount < 1 || supplierCount >= 6) {
    return chartXml;
  }
  const lastRow = 1 + supplierCount;
  return chartXml.replace(/(\$[A-Z]+\$2:\$[A-Z]+\$)7/g, `$1${lastRow}`);
}

type TemplateChart = {
  relId: string;
  chartXml: string;
  /** template paths of chartStyle / chartColorStyle parts, if present */
  stylePath: string | null;
  colorsPath: string | null;
  styleXml: string | null;
  colorsXml: string | null;
};

/** Resolves the RESUMEN worksheet part path inside a workbook ZIP. */
async function resolveResumenSheetPath(zip: JSZip): Promise<{ sheetPath: string; relId: string } | null> {
  const workbookXml = await readZipFile(zip, "xl/workbook.xml");
  const sheetEntry = workbookXml.match(
    new RegExp(`<sheet[^>]*name="${CHART_SHEET_NAME}"[^>]*r:id="(rId\\d+)"[^>]*/>`)
  );
  if (!sheetEntry) return null;
  const relId = sheetEntry[1];

  const workbookRels = await readZipFile(zip, "xl/_rels/workbook.xml.rels");
  const relMatch = workbookRels.match(new RegExp(`Id="${relId}"[^>]*Target="([^"]+)"`));
  if (!relMatch) return null;

  const target = relMatch[1].replace(/^\//, "").replace(/^xl\//, "");
  return { sheetPath: `xl/${target}`, relId };
}

function sheetNumberFromPath(sheetPath: string): string | null {
  return sheetPath.match(/sheet(\d+)\.xml$/)?.[1] ?? null;
}

// ── main export ───────────────────────────────────────────────────────────────

export async function injectDashboardCharts(
  outputPath: string,
  templatePath: string,
  supplierCount?: number
): Promise<void> {
  const count = supplierCount ?? 0;

  // 1. Load both ZIPs
  const [outputBuf, templateBuf] = await Promise.all([
    fs.readFile(outputPath),
    fs.readFile(templatePath),
  ]);
  const [outputZip, templateZip] = await Promise.all([
    JSZip.loadAsync(outputBuf),
    JSZip.loadAsync(templateBuf),
  ]);

  // 2. Read output manifest files
  const [workbookXml, workbookRelsXml, contentTypesXml] = await Promise.all([
    readZipFile(outputZip, "xl/workbook.xml"),
    readZipFile(outputZip, "xl/_rels/workbook.xml.rels"),
    readZipFile(outputZip, "[Content_Types].xml"),
  ]);

  // Guard: don't inject twice
  if (workbookXml.includes(`name="${CHART_SHEET_NAME}"`)) return;

  // 3. Resolve RESUMEN subtree inside the template
  const resumen = await resolveResumenSheetPath(templateZip);
  if (!resumen) throw new Error("injectDashboardCharts: template has no RESUMEN sheet");

  const tplSheetNum = sheetNumberFromPath(resumen.sheetPath);
  if (!tplSheetNum) throw new Error("injectDashboardCharts: cannot resolve template sheet number");

  const tplSheetXml = await readZipFile(templateZip, resumen.sheetPath);
  const tplSheetRels = await readZipFile(
    templateZip,
    `xl/worksheets/_rels/sheet${tplSheetNum}.xml.rels`
  );

  const drawingMatch = tplSheetRels.match(/drawings\/drawing(\d+)\.xml/);
  if (!drawingMatch) throw new Error("injectDashboardCharts: template RESUMEN has no drawing");
  const tplDrawingNum = drawingMatch[1];

  let tplDrawingXml = await readZipFile(templateZip, `xl/drawings/drawing${tplDrawingNum}.xml`);
  let tplDrawingRels = await readZipFile(
    templateZip,
    `xl/drawings/_rels/drawing${tplDrawingNum}.xml.rels`
  );

  // 4. Collect template charts (with their style/colors parts)
  const chartRelEntries = [
    ...tplDrawingRels.matchAll(/<Relationship[^>]*Id="(rId\d+)"[^>]*Target="[^"]*charts\/chart(\d+)\.xml"[^>]*\/>/g),
  ];

  const templateCharts: TemplateChart[] = [];
  for (const entry of chartRelEntries) {
    const relId = entry[1];
    const chartNum = entry[2];
    const chartXml = await readZipFile(templateZip, `xl/charts/chart${chartNum}.xml`);

    let stylePath: string | null = null;
    let colorsPath: string | null = null;
    let styleXml: string | null = null;
    let colorsXml: string | null = null;

    const chartRels = await readZipFileOptional(templateZip, `xl/charts/_rels/chart${chartNum}.xml.rels`);
    if (chartRels) {
      const styleMatch = chartRels.match(/Target="(style\d+\.xml)"/);
      const colorsMatch = chartRels.match(/Target="(colors\d+\.xml)"/);
      if (styleMatch) {
        stylePath = `xl/charts/${styleMatch[1]}`;
        styleXml = await readZipFileOptional(templateZip, stylePath);
      }
      if (colorsMatch) {
        colorsPath = `xl/charts/${colorsMatch[1]}`;
        colorsXml = await readZipFileOptional(templateZip, colorsPath);
      }
    }

    templateCharts.push({ relId, chartXml, stylePath, colorsPath, styleXml, colorsXml });
  }

  // 5. Drop the doughnut chart when there is no real comparison (1 supplier)
  const removedRelIds = new Set<string>();
  const chartsToInject = templateCharts.filter((chart) => {
    if (count === 1 && chart.chartXml.includes("doughnutChart")) {
      removedRelIds.add(chart.relId);
      return false;
    }
    return true;
  });

  for (const relId of removedRelIds) {
    // Remove the anchor block that embeds the removed chart…
    tplDrawingXml = tplDrawingXml.replace(
      /<xdr:twoCellAnchor>[\s\S]*?<\/xdr:twoCellAnchor>/g,
      (anchor) => (anchor.includes(`r:id="${relId}"`) ? "" : anchor)
    );
    // …and its relationship.
    tplDrawingRels = tplDrawingRels.replace(
      new RegExp(`<Relationship[^>]*Id="${relId}"[^>]*\\/>`),
      ""
    );
  }

  // 6. Allocate part numbers in the output
  const nextSheet = maxNumberedFiles(outputZip, /xl\/worksheets\/sheet(\d+)\.xml$/) + 1;
  const nextDrawing = maxNumberedFiles(outputZip, /xl\/drawings\/drawing(\d+)\.xml$/) + 1;
  const chartBase = Math.max(
    maxNumberedFiles(outputZip, /xl\/charts\/chart(\d+)\.xml$/),
    maxNumberedFiles(outputZip, /xl\/charts\/style(\d+)\.xml$/),
    maxNumberedFiles(outputZip, /xl\/charts\/colors(\d+)\.xml$/)
  );
  const nextRId = maxRId(workbookRelsXml) + 1;
  const nextSheetId = maxSheetId(workbookXml) + 1;

  const sheetPath = `xl/worksheets/sheet${nextSheet}.xml`;
  const sheetRelsPath = `xl/worksheets/_rels/sheet${nextSheet}.xml.rels`;
  const drawingPath = `xl/drawings/drawing${nextDrawing}.xml`;
  const drawingRelsPath = `xl/drawings/_rels/drawing${nextDrawing}.xml.rels`;

  // 7. Write charts (+ rels + style/colors) and patch drawing rels targets
  const overrides: string[] = [
    `<Override PartName="/${sheetPath}" ContentType="${CT_WORKSHEET}"/>`,
    `<Override PartName="/${drawingPath}" ContentType="${CT_DRAWING}"/>`,
  ];

  let patchedDrawingRels = tplDrawingRels;
  for (const [index, chart] of chartsToInject.entries()) {
    const chartNum = chartBase + index + 1;
    const chartPath = `xl/charts/chart${chartNum}.xml`;

    outputZip.file(chartPath, trimChartRanges(chart.chartXml, count));
    overrides.push(`<Override PartName="/${chartPath}" ContentType="${CT_CHART}"/>`);

    const chartRelLines: string[] = [];
    if (chart.styleXml) {
      const stylePart = `xl/charts/style${chartNum}.xml`;
      outputZip.file(stylePart, chart.styleXml);
      overrides.push(`<Override PartName="/${stylePart}" ContentType="${CT_CHART_STYLE}"/>`);
      chartRelLines.push(
        `<Relationship Id="rId1" Type="http://schemas.microsoft.com/office/2011/relationships/chartStyle" Target="style${chartNum}.xml"/>`
      );
    }
    if (chart.colorsXml) {
      const colorsPart = `xl/charts/colors${chartNum}.xml`;
      outputZip.file(colorsPart, chart.colorsXml);
      overrides.push(`<Override PartName="/${colorsPart}" ContentType="${CT_CHART_COLORS}"/>`);
      chartRelLines.push(
        `<Relationship Id="rId2" Type="http://schemas.microsoft.com/office/2011/relationships/chartColorStyle" Target="colors${chartNum}.xml"/>`
      );
    }
    if (chartRelLines.length > 0) {
      outputZip.file(
        `xl/charts/_rels/chart${chartNum}.xml.rels`,
        `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${chartRelLines.join("")}</Relationships>`
      );
    }

    // Point the drawing relationship of this chart at its new part name.
    patchedDrawingRels = patchedDrawingRels.replace(
      new RegExp(`(<Relationship[^>]*Id="${chart.relId}"[^>]*Target=")[^"]*("[^>]*\\/>)`),
      `$1/${chartPath}$2`
    );
  }

  const patchedSheetRels = tplSheetRels.replace(
    /Target="[^"]*drawing\d+\.xml"/,
    `Target="/${drawingPath}"`
  );

  // 8. Write sheet + drawing parts
  outputZip.file(sheetPath, tplSheetXml);
  outputZip.file(sheetRelsPath, patchedSheetRels);
  outputZip.file(drawingPath, tplDrawingXml);
  outputZip.file(drawingRelsPath, patchedDrawingRels);

  // 9. Patch workbook.xml / workbook rels / content types
  const updatedWorkbook = workbookXml.replace(
    "</sheets>",
    `<sheet name="${CHART_SHEET_NAME}" sheetId="${nextSheetId}" r:id="rId${nextRId}"/></sheets>`
  );
  const updatedWorkbookRels = workbookRelsXml.replace(
    "</Relationships>",
    `<Relationship Id="rId${nextRId}" Type="${WORKSHEET_TYPE}" Target="worksheets/sheet${nextSheet}.xml"/></Relationships>`
  );
  const updatedContentTypes = contentTypesXml.replace("</Types>", `${overrides.join("")}</Types>`);

  outputZip.file("xl/workbook.xml", updatedWorkbook);
  outputZip.file("xl/_rels/workbook.xml.rels", updatedWorkbookRels);
  outputZip.file("[Content_Types].xml", updatedContentTypes);

  // 10. Re-pack and overwrite the output file
  const buffer = await outputZip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  await fs.writeFile(outputPath, buffer);
}

// ── strip helper ──────────────────────────────────────────────────────────────

/**
 * Removes the injected RESUMEN sheet (worksheet, drawing, charts and their
 * chartStyle/chartColorStyle parts) from the output file so ExcelJS can safely
 * re-read it (ExcelJS crashes on chart anchors).
 * Returns true if charts were found and removed, false if nothing to strip.
 * After your ExcelJS operation, call injectDashboardCharts again to restore.
 */
export async function stripDashboardCharts(outputPath: string): Promise<boolean> {
  const buf = await fs.readFile(outputPath);
  const zip = await JSZip.loadAsync(buf);

  const [workbookXml, workbookRelsXml, contentTypesXml] = await Promise.all([
    readZipFile(zip, "xl/workbook.xml"),
    readZipFile(zip, "xl/_rels/workbook.xml.rels"),
    readZipFile(zip, "[Content_Types].xml"),
  ]);

  const resumen = await resolveResumenSheetPath(zip);
  if (!resumen) return false;

  const sheetNum = sheetNumberFromPath(resumen.sheetPath);
  if (!sheetNum) return false;

  const sheetPath = resumen.sheetPath;
  const sheetRelsPath = `xl/worksheets/_rels/sheet${sheetNum}.xml.rels`;
  const partsToRemove: string[] = [sheetPath];

  // Resolve drawing from sheet rels
  let drawingNum: string | null = null;
  const sheetRelsXml = await readZipFileOptional(zip, sheetRelsPath);
  if (sheetRelsXml) {
    partsToRemove.push(sheetRelsPath);
    const dm = sheetRelsXml.match(/drawings\/drawing(\d+)\.xml/);
    if (dm) {
      drawingNum = dm[1];
      partsToRemove.push(`xl/drawings/drawing${drawingNum}.xml`);
    }
  }

  // Resolve charts (and their style/colors parts) from drawing rels
  if (drawingNum) {
    const drawingRelsPath = `xl/drawings/_rels/drawing${drawingNum}.xml.rels`;
    const drawingRelsXml = await readZipFileOptional(zip, drawingRelsPath);
    if (drawingRelsXml) {
      partsToRemove.push(drawingRelsPath);
      for (const m of drawingRelsXml.matchAll(/charts\/chart(\d+)\.xml/g)) {
        const chartNum = m[1];
        const chartPath = `xl/charts/chart${chartNum}.xml`;
        partsToRemove.push(chartPath);

        const chartRelsPath = `xl/charts/_rels/chart${chartNum}.xml.rels`;
        const chartRelsXml = await readZipFileOptional(zip, chartRelsPath);
        if (chartRelsXml) {
          partsToRemove.push(chartRelsPath);
          for (const part of chartRelsXml.matchAll(/Target="((?:style|colors)\d+\.xml)"/g)) {
            partsToRemove.push(`xl/charts/${part[1]}`);
          }
        }
      }
    }
  }

  for (const part of partsToRemove) {
    zip.remove(part);
  }

  // Patch workbook.xml
  const updatedWorkbook = workbookXml.replace(
    new RegExp(`<sheet[^>]*name="${CHART_SHEET_NAME}"[^>]*\\/>`, "g"),
    ""
  );

  // Patch workbook.xml.rels
  const updatedWorkbookRels = workbookRelsXml.replace(
    new RegExp(`<Relationship[^>]*Id="${resumen.relId}"[^>]*\\/>`),
    ""
  );

  // Patch [Content_Types].xml
  let updatedContentTypes = contentTypesXml;
  for (const part of partsToRemove) {
    if (part.endsWith(".rels")) continue;
    const escaped = part.replace(/[/\\.]/g, (char) => `\\${char}`);
    updatedContentTypes = updatedContentTypes.replace(
      new RegExp(`<Override[^>]*PartName="/${escaped}"[^>]*/>`),
      ""
    );
  }

  zip.file("xl/workbook.xml", updatedWorkbook);
  zip.file("xl/_rels/workbook.xml.rels", updatedWorkbookRels);
  zip.file("[Content_Types].xml", updatedContentTypes);

  const cleaned = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
  await fs.writeFile(outputPath, cleaned);
  return true;
}
